server:
  port: 9001

# feign开启hystrix熔断器
feign:
  hystrix:
    enabled: true


eureka:
  client: #客户端注册进eureka服务列表内
    register-with-eureka: false #false表示不向注册中心注册自己
    service-url:
      #defaultZone: http://localhost:7001/eureka #单机版
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/